version: '3'
services:
  db:
    image: postgres:11.14-alpine
    container_name: postgres
    ports:
      - 5432:5434
    volumes:
     - ./data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_BD: message_broker
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always

  message_broker:
    image: message_broker_image
    container_name: message_broker_container
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - db